In [2]:
import pandas as pd
import glob
import os

# read csv from 01_raw and merge them into one
raw_data_dir = r"C:\GitHub\mlops-rapidkl\data\01_raw"
csv_files = glob.glob(os.path.join(raw_data_dir, "rapidrail_*_daily.csv"))

dfs = []
for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)
print(f"Merged data shape: {merged_df.shape}")
merged_df.head()

Merged data shape: (18918326, 4)

             origin         destination        date  ridership
0  A0: All Stations  AG01: Sentul Timur  2023-04-01       1668
1  A0: All Stations  AG01: Sentul Timur  2023-04-02         51
2  A0: All Stations  AG01: Sentul Timur  2023-04-03          2
3  A0: All Stations  AG01: Sentul Timur  2023-04-04          2
4  A0: All Stations  AG01: Sentul Timur  2023-04-05          3

In [4]:
# count of data for each pair
pair_counts = merged_df.groupby(['origin', 'destination']).size().reset_index(name='count')
pair_counts.sort_values(by='count', ascending=False, inplace=True)
display(pair_counts.head(20))

                    origin             destination  count
16903  SP31: Putra Heights     SP31: Putra Heights   1120
0         A0: All Stations      AG01: Sentul Timur   1120
1         A0: All Stations            AG02: Sentul   1120
2         A0: All Stations        AG03: Titiwangsa   1120
3         A0: All Stations              AG04: PWTC   1120
4         A0: All Stations     AG05: Sultan Ismail   1120
5         A0: All Stations         AG06: Bandaraya   1120
6         A0: All Stations      AG07: Masjid Jamek   1120
16887  SP31: Putra Heights     SP13: Salak Selatan   1120
16886  SP31: Putra Heights            SP12: Cheras   1120
16885  SP31: Putra Heights     PYL04: Sungai Buloh   1120
16884  SP31: Putra Heights  PYL03: Kampung Selamat   1120
16883  SP31: Putra Heights        MR11: Titiwangsa   1120
16882  SP31: Putra Heights          MR10: Chow Kit   1120
16881  SP31: Putra Heights      MR09: Medan Tuanku   1120
16880  SP31: Putra Heights       MR08: Bukit Nanas   1120
16879  SP31: Putra Heights       MR07: Raja Chulan   1120
16878  SP31: Putra Heights     MR06: Bukit Bintang   1120
16877  SP31: Putra Heights              MR05: Imbi   1120
16876  SP31: Putra Heights         MR04: Hang Tuah   1120

In [5]:
# count of data for each pair
pair_counts = merged_df.groupby(['origin', 'destination']).size().reset_index(name='count')
pair_counts.sort_values(by='count', ascending=False, inplace=True)
display(pair_counts.head(20))

                    origin             destination  count
16903  SP31: Putra Heights     SP31: Putra Heights   1120
0         A0: All Stations      AG01: Sentul Timur   1120
1         A0: All Stations            AG02: Sentul   1120
2         A0: All Stations        AG03: Titiwangsa   1120
3         A0: All Stations              AG04: PWTC   1120
4         A0: All Stations     AG05: Sultan Ismail   1120
5         A0: All Stations         AG06: Bandaraya   1120
6         A0: All Stations      AG07: Masjid Jamek   1120
16887  SP31: Putra Heights     SP13: Salak Selatan   1120
16886  SP31: Putra Heights            SP12: Cheras   1120
16885  SP31: Putra Heights     PYL04: Sungai Buloh   1120
16884  SP31: Putra Heights  PYL03: Kampung Selamat   1120
16883  SP31: Putra Heights        MR11: Titiwangsa   1120
16882  SP31: Putra Heights          MR10: Chow Kit   1120
16881  SP31: Putra Heights      MR09: Medan Tuanku   1120
16880  SP31: Putra Heights       MR08: Bukit Nanas   1120
16879  SP31: Putra Heights       MR07: Raja Chulan   1120
16878  SP31: Putra Heights     MR06: Bukit Bintang   1120
16877  SP31: Putra Heights              MR05: Imbi   1120
16876  SP31: Putra Heights         MR04: Hang Tuah   1120